# dataset: Name of dataset
# mode: pgo, vio, ba
# K: Period of ISAM2 updates
# epsilon: Error tolerance
# max_iter: Number of inner loop iterations
# d_error: If error does not reduce more than d_error, we consider it converged
# relinearize_skip: Number of steps between relinearization of variable. Set this to 1
# print_frequency: Frequency of printing
# num_steps: Maximum steps
# relin_threshold: Delta norm to relinearize variable
# lc_steps_file: File listing all the loop closure steps
# lc_lookahead: How many steps before the LC step to run factorization
# igo_id: The type of incremental solver to use
# is_3D: True if 3D dataset

dataset: "w10000"
is_3D: false
igo_id: "iterative"
mode: "pgo"
relin_threshold: 0.001
lc_lookahead: 1
lc_steps_file: "/home/ubuntu/slam-experiments/2023-12-10_project-experiments/data/w10000_selected_steps.txt"
default_num_outer_iter: 4
profile_outer_iter: 1
max_cg_iter: 500
cg_tolerance: 1e-10
stop_step: 3000

selchol:
  min_sel_rows: 0
  percent_rows: 0.05

boundeddiff:
  row_norm_bound: 0.2
  max_norm_bound: 0.9

profile_lc_step: 931
profile_lc_step_only: True
output_file: "/dev/null"
